name: SurvivalPlugin
version: @version@
main: xyz.n7mn.dev.survivalplugin.SurvivalPlugin
api-version: 1.17
load: POSTWORLD
authors: [ 7mi_chan ]
description: SurvivalPlugin
commands:
  sigen:
    usage: '/sigen'
    description: ''
  main:
    usage: '/main'
    description: ''
  user:
    usage: '/user <mcid>'
    description: ''
    permission: '7miseikatu.op'
    permission-message: ''
  sethome:
    usage: '/sethome'
    description: ''
  home:
    usage: '/home'
    description: ''
  delhome:
    usage: '/delhome'
    description: ''
  spawn:
    usage: '/spawn'
    description: ''
  noti:
    usage: '/noti'
    description: ''
  lock:
    usage: '/lock'
    description: ''
  unlock:
    usage: '/unlock'
    description: ''

  de:
    usage: '/de'
    description: ''
    permission: '7miseikatu.op'